# Generated by Django 3.1.3 on 2020-12-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201202_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Categories',
            field=models.ManyToManyField(related_name='category_posts', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Tags',
            field=models.ManyToManyField(related_name='tag_posts', to='blog.Tag'),
        ),
    ]
