# Generated by Django 3.1.3 on 2020-12-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201203_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned_on_main_bottom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned_on_main_top',
            field=models.BooleanField(default=False),
        ),
    ]
