# Generated by Django 3.1.3 on 2020-12-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201203_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_trending',
        ),
    ]
