# Generated by Django 3.1.3 on 2021-01-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210114_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
