# Generated by Django 3.1.3 on 2021-01-17 11:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='tg_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
