# Generated by Django 3.1.3 on 2021-01-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210117_1324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloguser',
            unique_together=set(),
        ),
    ]
