# Generated by Django 3.1.3 on 2021-01-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210117_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='social_picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='avatar_image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='static/users_images', verbose_name='Image'),
        ),
    ]
