# Generated by Django 3.1.3 on 2021-01-22 17:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210122_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_rendered',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
