# Generated by Django 3.1.5 on 2021-01-30 12:50

from django.db import migrations


def create_settings(apps, schema_editor):
    MySiteSettings = apps.get_model('blog', 'SiteSettings')
    MySiteSettings.objects.get_or_create()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210130_1444'),
    ]

    operations = [
        migrations.RunPython(create_settings),
    ]
