# Generated by Django 3.1.5 on 2021-01-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20210130_1450'),
    ]

    operations = [
    ]
