# Generated by Django 3.1.5 on 2021-01-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20210130_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_about_text',
            field=models.TextField(blank=True, max_length=510, null=True),
        ),
    ]
