# Generated by Django 3.1.5 on 2021-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20210130_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='github_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
